apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  #  namespace: microservice-namespace
  labels:
    app: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          image: juanyee/discovery-server
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
#  namespace: microservice-namespace
spec:
  type: ClusterIP
  selector:
    app: discovery
  ports:
    - name: http
      protocol: TCP
      port: 8761
