apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  #  namespace: microservice-namespace
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: juanyee/order-service
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_DEFAULT_ZONE
              value: http://discovery-service:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
#  namespace: microservice-namespace
spec:
  type: LoadBalancer
  selector:
    app: order
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
